# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

strategy:
  matrix:
    jdk11_windows:
      imageName: "windows-latest"
      jdkVersion: "17"
  maxParallel: 2

pool:
  vmImage: windows-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(jdkVersion)
    mavenVersionOption: 'Default'
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: "**/SparkReport.html"
    goals: "package"
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

